version: "3"

services:
  volt:
    image: sahilsaini787/volt
    container_name: volt
    hostname: https://sahil.y.llm.lat
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - nginx-proxy-net

networks:
  nginx-proxy-net:
    external: true
    driver: bridge
