version: "3"

services:
  volt:
    image: sahilsaini787/volt
    container_name: volt
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - nginx-proxy-net

networks:
  nginx-proxy-net:
    external: true
