name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4

    - 
      name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
            
    - name: Build the Docker image
      run: |
        docker build . \
          --file Dockerfile \
          --tag sahilsaini787/volt:latest \
          --build-arg GRAPHQL_API_URL=${{ secrets.GRAPHQL_API_URL }} \
          --build-arg NEXT_PUBLIC_OPEN_WEATHER_API=${{ secrets.NEXT_PUBLIC_OPEN_WEATHER_API }} \
          --build-arg SITE_URL=${{ secrets.SITE_URL }}      


    - name: Push Docker image to Dockerhub
      run: | 
            docker push sahilsaini787/volt:latest
