name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sahilsaini787/volt:latest

    - name: Push Docker image to Dockerhub
      run: | 
            docker push sahilsaini787/volt:latest
